ktor {
    deployment {
        port = 8080
    }
    application {
        modules = [ com.wardrobeapp.server.ApplicationKt.module ]
    }
}

database {
    url = ${DATABASE_URL}
}

jwt {
    secret = ${JWT_SECRET}
    issuer = "wardrobe-app"
    audience = "wardrobe-users"
    realm = "wardrobe"
}

cloudinary {
    cloudName = ${CLOUDINARY_CLOUD_NAME}
    apiKey = ${CLOUDINARY_API_KEY}
    apiSecret = ${CLOUDINARY_API_SECRET}
}